name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: testing logs
        run: |
          echo Hello world!
          echo "::error file=test.py,line=27::error annotation"
          echo "::error:: just an error:: message"
          echo "::debug just a debug message"
          echo "::debug:: just a debug:: message"
          echo "::debug::just a debug::message"
          echo "::notice just a notice"
          echo "::notice title=notícia::just a propper notice"
          echo "::group::My title"
          echo "Inside group"
          echo "Inside group"
          echo "::endgroup::"
