name: Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo Hello world!
          echo "::error file=test.py,line=27::Hardcoded number"
          echo "::error:: just an error:: message"
          echo "::debug just a debug message"
          echo "::debug:: just a debug:: message"
          echo "::debug::just a debug::message"
